### ISSUE TITLE
Build a coffea-casa-dask version with pinned packages for EAF compatiblity

### ISSUE THREAD

**Issue by mapsacosta** [CoffeaTeam/docker-coffea-dask#45]
I would like to enable the use of the `coffea-casa-dask` image for Dask clusters launched from the EAF's dask-gateway server. 

Dask is very cranky when client and server versions of some packages differ (see issue [here](https://github.com/dask/dask-gateway/issues/252#issuecomment-623724315)). We have not been able to use the dask-cc7 image out of the box in production yet as I need to set the client with the exact same versions at the image for workers/scheduler.

EAF images have [pinned versions](https://github.com/mapsacosta/EAFJupyter/blob/f44e4f67e2bd0affd9366732090ad63a00b7dfe9/dask-notebook/Dockerfile#L29) to avoid mismatching `distributed` versions causing issues, but for the coffea-casa-dask image, pinned versions in the code seem to be changing extremely fast.

I noticed this repo has a GH actions workflow that changes pinned versions constantly, which is not operationally sustainable for us neither it fits the production CI pipeline for the EAF. There are multiple ways to solve this, but basically we need to make sure at least dask, distributed and dask-gateway are pinned in a "stable" way. 

Any ideas on how to make this happen?

CC. @holzman

Edit: Typo

**Comment by holzman** [comment]
+1. Having more stability in the release process is a good idea generally (not just to keep server and client versions in sync).

**Comment by oshadura** [comment]
Thanks for your report! 

Do you know if `dask, distributed` have a recommended version to use with `dask-gateway`? As I see from point of view of releases `dask-gateway` they don't have any new releases during last year: https://github.com/dask/dask-gateway/tags, while `dask` and `distributed` have a monthly release.  I think you have a valid point, but we probably need to report it in `dask-gateway` repository and to ask `dask` community to test and release matching versions? If you want I can open an issue to understand how we can proceed.

Other thing I noticed is that you are using mismatched versions which is _highly_ not recommended by dask:
```dask==2.30.0 \
 distributed==2.30.1 \```
(also please take in account that `dask 2.30.0` was released almost one year ago: https://docs.dask.org/en/latest/changelog.html#id19)

We have pinned `dask` and `distributed` packages according releases since there is a continuous improvements and bug fixes (including security fixes). Sadly we don't have an image with Dask 2.30.0, since we created this repository much more later...

As a small comment from `coffea-casa` prospective if we don't update often version of `dask`/`distributed`(like each 2-3 month), it is really hard after to update all versions together.

@holzman  @mapsacosta I also would like to propose if would you like to meet all together and discuss what we can do to make this repository more usable for your case?

**Comment by mapsacosta** [comment]
Fortunately, this seems to be known in the dask-gateway community and a release is on the horizon: https://github.com/dask/dask-gateway/issues/381#issuecomment-909774349

Here are a couple issues that mention this same versioning discrepancies, I will follow them closely:
https://github.com/dask/dask-gateway/issues/376
https://github.com/dask/dask-gateway/issues/161

**Comment by oshadura** [comment]
Resolved, see image in https://hub.docker.com/repository/docker/coffeateam/coffea-dask-cc7-gateway
